name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      # Ми просто пропустимо сувору перевірку типів, яка свариться на очікувані помилки
      # і запустимо відразу тести, які перевірять твою логіку
      - run: npm test
